auth0:
  domain: your-tenant.auth0.com
  client_id: EDGE_CLIENT_ID
  client_secret: EDGE_CLIENT_SECRET
  edge_audience: https://edge-api.yourcorp.com

tools:
  hr_api:
    audience: https://hr-api.yourcorp.com
    openapi: https://hr-api.yourcorp.com/openapi.json
  crm_api:
    audience: https://crm-api.yourcorp.com
    openapi: https://crm-api.yourcorp.com/openapi.json
